// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziovlchviowdrktgbazl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inppb3ZsY2h2aW93ZHJrdGdiYXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDM4NTAsImV4cCI6MjA3MDAxOTg1MH0.eI3-s3ARByUjofFVBbULZLBbRSYXf7En6NAQQ2hRhB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});